### ISSUE TITLE
Private Equity as part of Total Compensation

### ISSUE THREAD

**Issue by jndietz** [emilepetrone/financial_lessons#2]
How is private equity valuable if the company never sells or goes public?  It just seems like funny money at that point.

Is the endgame for every startup to go public at some point?

It feels a little disingenuous to include private equity as part of total comp since the company may never go public or get bought.

**Comment by emilepetrone** [comment]
You've hit the nail on the head. 3 options - either the company is acquired, goes public, or you try and sell it privately (in a number of ways). If you never have an exit, then it's paper. I have some stock in a private company that I doubt will ever go public or be acquired. I am in the exact situation you describe.

**Comment by emilepetrone** [comment]
Heads up - I've started a series of posts on Equity Compensation. The first was this week, with more coming each week from here on.
